export const METRIC_GLOSSARY = {
  candidateRank: 'This is AlphaPilot\'s recommendation priority under the selected ranking policy. You are not required to add positions in this order.',
  strategySignal: 'What the selected deterministic strategy requests from stored data. A signal is not automatically a portfolio action.',
  portfolioDecision: 'What the portfolio policy approves after holdings, cash, rank, sizing, and constraints. It is advisory and sends no order.',
  rs20: 'Stock 20-trading-bar return minus SPY 20-bar return on the signal day. Higher scores rank BUY candidates first; negative does not mean invalid.',
  referencePrice: 'The stored price used by the backend for this advisory calculation. It is not a live quote or guaranteed fill.',
  atr14: 'Average True Range over 14 trading bars through the analysis day. It measures recent price movement; higher is more volatile, not inherently better or worse.',
  stopDistance: 'Two times ATR14, used only as AlphaPilot’s research sizing-risk proxy. It is not an executable stop loss.',
  stopReference: 'Reference price minus the 2×ATR14 research distance. It is not an active stop order and is not a validated production exit rule.',
  proposedShares: 'Whole shares approved by the backend sizing and constraint policy. The browser does not recalculate this amount.',
  proposedAllocation: 'Backend-estimated cash allocated to the proposed shares at the reference price. It is advisory, not an order total.',
  targetWeight: 'Proposed allocation as a percentage of submitted portfolio equity. Context and portfolio constraints matter more than high or low alone.',
  riskBudget: 'Maximum research risk budget considered for this candidate under the selected policy; it is not a loss guarantee.',
  modeledPositionRisk: 'Proposed shares multiplied by the modeled 2×ATR14 distance. It is a proxy and does not model gaps or actual stop execution.',
  sector: 'Stored company sector used for entry concentration constraints. Missing values remain Unclassified and are never inferred in the browser.',
  sectorBefore: 'Submitted portfolio market value in this sector before the proposed entry, as a percentage of equity.',
  sectorAfter: 'Modeled sector weight after the proposed entry. The cap applies at entry; later market drift is not force-rebalanced.',
  currentShares: 'Shares in the submitted research portfolio snapshot. This is browser-supplied research state, not broker-synchronized state.',
  estimatedProceeds: 'Backend-estimated cash received by closing the submitted whole position at its reference value. No broker fill is implied.',
  estimatedOutlay: 'Exact backend workflow cash impact for adding the approved position to research draft state. It is not a broker charge.',
  decisionReason: 'Stable backend reason code explaining why the portfolio action was approved, held, or skipped.',
} as const
