import type { PortfolioPlan, PortfolioRiskConfig } from '../types/portfolio'

export const riskConfigFixture: PortfolioRiskConfig = {
  risk_per_position_pct: '1',
  atr_period: 14,
  atr_stop_multiple: '2',
  max_position_weight_pct: '10',
  max_portfolio_risk_pct: '8',
  minimum_cash_reserve_pct: '10',
  max_sector_weight_pct: '30',
  max_positions: 10,
}

export const planFixture: PortfolioPlan = {
  plan_id: 'fixture-plan-20260820',
  portfolio: {
    equity: '100000',
    cash: '30000',
    cash_pct: '30',
    invested_value: '70000',
    invested_pct: '70',
    cash_reserve_requirement: '10000',
    current_portfolio_risk: '4200',
    current_portfolio_risk_pct: '4.2',
    available_portfolio_risk: '3800',
    available_portfolio_risk_pct: '3.8',
    modeled_risk_complete: false,
    open_positions: 2,
    positions: [
      {
        ticker: 'MSFT',
        shares: 100,
        reference_price: '400',
        market_value: '40000',
        portfolio_weight_pct: '40',
        cost_basis: '350',
        sector: 'Information Technology',
        modeled_risk_dollars: '2200',
      },
      {
        ticker: 'JNJ',
        shares: 200,
        reference_price: '150',
        market_value: '30000',
        portfolio_weight_pct: '30',
        cost_basis: null,
        sector: 'Health Care',
        modeled_risk_dollars: '2000',
      },
    ],
  },
  config: riskConfigFixture,
  strategy: 'ema20-pullback',
  selection_policy: 'relative-strength-20',
  sizing_policy: 'equal-slot',
  requested_as_of_date: '2026-08-23',
  analysis_as_of_date: '2026-08-20',
  evaluation_target_ticker: null,
  decisions: [
    {
      ticker: 'NVDA', signal: 'BUY', decision: 'BUY', reason: 'BUY_APPROVED',
      ranking_score: '0.08421', reference_price: '180', atr: '4.2', stop_distance: '8.4',
      risk_budget_dollars: '1000', target_allocation_dollars: '9900', target_weight_pct: '9.9',
      proposed_shares: 55, modeled_position_risk_dollars: '462', sector: 'Information Technology',
      sector_weight_before_pct: '20', sector_weight_after_pct: '29.9', current_shares: 0,
      estimated_proceeds: null, normalized_sizing_weight: null,
      estimated_cash_outlay: '9900', cash_after_decision: '50100', modeled_stop_reference_price: '171.6',
      action_id: '1:BUY:NVDA', application_order: 1, depends_on_action_ids: [],
      exit_context: {
        strategy: 'ema20-pullback', data_as_of_date: '2026-08-20', reference_close: '180',
        current_signal: 'BUY', signal_reason: 'EMA20_PULLBACK_RECLAIM', exit_mode: 'hybrid-2%',
        current_exit_state: 'ABOVE_EMA20', fixed_take_profit_policy: 'NONE',
        ema20: '175', ema50: '165', ema_spread_pct: '6.0606', hybrid_threshold_pct: '2',
        distance_to_ema20_pct: '2.8571', distance_to_ema50_pct: '9.0909', sma150: null,
        distance_to_sma150_pct: null,
      },
    },
    {
      ticker: 'JNJ', signal: 'SELL', decision: 'SELL', reason: 'SELL_APPROVED',
      ranking_score: null, reference_price: '150', atr: null, stop_distance: null,
      risk_budget_dollars: '0', target_allocation_dollars: '0', target_weight_pct: '0',
      proposed_shares: 0, modeled_position_risk_dollars: '0', sector: 'Health Care',
      sector_weight_before_pct: '0', sector_weight_after_pct: '0', current_shares: 200,
      estimated_proceeds: '30000', normalized_sizing_weight: null,
      estimated_cash_outlay: null, cash_after_decision: '60000', modeled_stop_reference_price: null,
      action_id: '2:SELL:JNJ', application_order: 2, depends_on_action_ids: [], exit_context: null,
    },
    {
      ticker: 'MSFT', signal: 'HOLD', decision: 'HOLD', reason: 'NO_ACTION',
      ranking_score: null, reference_price: '400', atr: null, stop_distance: null,
      risk_budget_dollars: '0', target_allocation_dollars: '0', target_weight_pct: '0',
      proposed_shares: 0, modeled_position_risk_dollars: '0', sector: 'Information Technology',
      sector_weight_before_pct: '0', sector_weight_after_pct: '0', current_shares: 100,
      estimated_proceeds: null, normalized_sizing_weight: null,
      estimated_cash_outlay: null, cash_after_decision: null, modeled_stop_reference_price: null,
      action_id: null, application_order: null, depends_on_action_ids: [], exit_context: null,
    },
    {
      ticker: 'AAPL', signal: 'BUY', decision: 'SKIP', reason: 'SECTOR_LIMIT',
      ranking_score: '-0.0123', reference_price: '220', atr: '5', stop_distance: '10',
      risk_budget_dollars: '1000', target_allocation_dollars: '0', target_weight_pct: '0',
      proposed_shares: 0, modeled_position_risk_dollars: '0', sector: 'Information Technology',
      sector_weight_before_pct: '29.9', sector_weight_after_pct: '29.9', current_shares: 0,
      estimated_proceeds: null, normalized_sizing_weight: null,
      estimated_cash_outlay: null, cash_after_decision: null, modeled_stop_reference_price: null,
      action_id: null, application_order: null, depends_on_action_ids: [], exit_context: null,
    },
  ],
  candidate_statuses: [
    { ticker: 'NVDA', status: 'READY', data_as_of_date: '2026-08-20', signal: 'BUY', reason: 'EMA20_PULLBACK_RECLAIM', company_name: 'NVIDIA Corporation', company_id: '11111111-1111-4111-8111-111111111111', sector: 'Information Technology', ranking_score: '0.08421', atr: '4.2', decision: 'BUY', decision_reason: 'BUY_APPROVED', candidate_rank: 1 },
    { ticker: 'OLD', status: 'STALE_DATA', data_as_of_date: '2026-08-19', signal: null, reason: 'STALE_DATA', company_name: 'Old Company', company_id: '22222222-2222-4222-8222-222222222222', sector: 'Industrials', ranking_score: null, atr: null, decision: null, decision_reason: null, candidate_rank: null },
    { ticker: 'NEW', status: 'INSUFFICIENT_HISTORY', data_as_of_date: '2026-08-20', signal: 'HOLD', reason: 'INSUFFICIENT_DATA', company_name: 'New Company', company_id: '33333333-3333-4333-8333-333333333333', sector: null, ranking_score: null, atr: null, decision: null, decision_reason: null, candidate_rank: null },
  ],
  readiness: {
    status: 'PARTIAL_DATA', requested_tickers: 3, evaluated_tickers: 1,
    fresh_tickers: 2, stale_tickers: 1, no_data_tickers: 0,
    insufficient_history_tickers: 1, company_not_found_tickers: 0,
    buy_signals: 1, approved_buys: 1, approved_sells: 1,
    actionable_decisions: 2, latest_ticker_data_date: '2026-08-20',
    buy_rejections_by_reason: {},
  },
}
