"""create initial schema

Revision ID: 324bbc9aff60
Revises: 
Create Date: 2026-08-03 11:07:51.518765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324bbc9aff60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_index('ix_companies_exchange', 'companies', ['exchange'], unique=False)
    op.create_index('ix_companies_sector', 'companies', ['sector'], unique=False)
    op.create_index('ix_companies_ticker', 'companies', ['ticker'], unique=False)
    op.create_table('daily_candles',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'trading_day', name='uq_daily_candle_company_day')
    )
    op.create_index('ix_daily_candles_company', 'daily_candles', ['company_id'], unique=False)
    op.create_index('ix_daily_candles_day', 'daily_candles', ['trading_day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_candles_day', table_name='daily_candles')
    op.drop_index('ix_daily_candles_company', table_name='daily_candles')
    op.drop_table('daily_candles')
    op.drop_index('ix_companies_ticker', table_name='companies')
    op.drop_index('ix_companies_sector', table_name='companies')
    op.drop_index('ix_companies_exchange', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
